### ISSUE TITLE
Windows corefoundation_lib?? Glew link errors

### ISSUE THREAD

**Issue by wini3d** [Shervanator/Engine#19]
Hi, where do I find this package? "corefoundation_lib" This looks like OSX library??

**Comment by Shervanator** [comment]
Hey! I've just pushed a change to remove the dependancy on corefoundation https://github.com/Shervanator/Engine/commit/ffd22b9c6f634c146f193a3fcbc3a0c8bd354670 this library was never used.. I've never tested building the engine on windows yet, but as long as you have the other dependancies i see no reason for it not to work! We might need to modify these scripts: https://github.com/Shervanator/Engine/tree/master/CMakeModules just to help cmake find the dependancies on windows.

**Comment by Shervanator** [comment]
Let me know how things go!

**Comment by wini3d** [comment]
Thanks. I'm just having problems linking with glew32. Is it setup static or shared? I'm getting __imp___glewXXXXX errors.

maybe adding submodules as dependencies for Windows?

**Comment by wini3d** [comment]
If I link against the static library **libglew32.a** , I'm getting fewer linker errors but still..

```
[  2%] Linking CXX shared library libengine.dll
CMakeFiles\engine.dir/objects.a(GLEWManager.cpp.obj): In function `GLEWManager::GLEWManager()':
C:/test/Engine/src/GLEWManager.cpp:16: undefined reference to `__imp_glewExperimental'
C:/test/Engine/src/GLEWManager.cpp:17: undefined reference to `__imp_glewInit'
C:/test/Engine/src/GLEWManager.cpp:21: undefined reference to `__imp_glewGetErrorString'
C:/test/Engine/src/GLEWManager.cpp:24: undefined reference to `__imp_glewGetString'
collect2.exe: error: ld returned 1 exit status
CMakeFiles\engine.dir\build.make:1045: recipe for target 'libengine.dll' failed
mingw32-make[2]: *** [libengine.dll] Error 1
CMakeFiles\Makefile2:66: recipe for target 'CMakeFiles/engine.dir/all' failed
mingw32-make[1]: *** [CMakeFiles/engine.dir/all] Error 2
Makefile:126: recipe for target 'all' failed
mingw32-make: *** [all] Error 2
```
Any ideas?

**Comment by Shervanator** [comment]
Yeah i have thought about bundling deps as submodules, i think i should do it as it will fix other build issues with things like emscripten or android. But also i hesitated as it means i need to include a lot of extra stuff with this repo (although submodules makes this less of an issue) and also built times will also take into account building the other deps.

**Comment by Shervanator** [comment]
but moving to submodules will take me a little while. linking to glew32 should work :( where did you get the libglew32.a from? Maybe try getting the stuff from here: http://glew.sourceforge.net/install.html

**Comment by wini3d** [comment]
Sounds great. Of course, I have to build glew using my current toolchain/gcc which is 5.1 (MinGW). There was also a fix with creating static libraries for glew windows, I forgot where I got it because it was some time ago but it works. So was it static or dynamic/DLL lib for glew?

As for submodules, I assume you already know that you can easily do submodule links without copying the actual library projects, afaik and so you still keep a minimal size project if that's what you're aiming for.

I think with assimp and sdl it's not that hard when using cmake gui, it's the glew part that is a bit tricky and it depends on the project. Most works already has glew static in it with their preferred version.

**Comment by Shervanator** [comment]
Hey ive started to move the deps as submodules: https://github.com/Shervanator/Engine/pull/21 just need to get glm working then it should be done

**Comment by wini3d** [comment]
Sounds great! :smile:  Just a tip on Windows glm build, you just include the headers and don't need to build the libraries.

**Comment by Shervanator** [comment]
Hey so this has taken a while, but last night i got the engine building on windows with some extra hacks on top of https://github.com/Shervanator/Engine/pull/21 to make it work. But the engine was running what felt like 0.5 fps... so this will need more looking into :( but ive been refactoring all my cmake stuff to make it hopefully easier to do thing stuff in the future. Ive been using the visual studio 2013 toolchain for context.

**Comment by Shervanator** [comment]
So Ive fixed all the issues with buildign on windows now, the fps issue was because of this line: https://github.com/Shervanator/Engine/pull/21/commits/3877bf50d3f2b4c187bcc46d0ee7808e421468b0#diff-8fc097fa6ec08c6ff9021c83bd926d8bR58 this fixed it, something about swapping the back buffer was causing it.. The only thing left on the pr is getting android builds working again. After that i will merge it, will close this issue now, let me know if any other issues come up.

**Comment by wini3d** [comment]
Thanks, I will be waiting for a stable release on Windows!
