### ISSUE TITLE
Link GLEW as static library

### ISSUE THREAD

**Issue by wini3d** [Shervanator/Engine#20]
Maybe to avoid cross platform errors, since you mentioned that you have never tried building it in Windows, perhaps a suggestion on Glew library linking as explained here..

> 
> 
> Add glew.c to your project. Just compile it in with the rest of your source files. As long as you #define GLEW_STATIC it will work fine. Problem solved.
> 
> Even if you succeed at linking it to the library, you are then bound to one specific architecture/build/version. If you just include glew.c you will be free to build the project virtually anywhere.

http://stackoverflow.com/a/12427214/4397269

I know there's a pre-build with glew sources, so maybe just add thirdparty or dependencies folder and place it depending on platform?? or just with Windows if it is an isolated case.

Just throwing out some suggestions for cross-platform building..

**Comment by Shervanator** [comment]
this is fixed in this pr https://github.com/Shervanator/Engine/pull/21 we now build glew as a shared lib
