### ISSUE TITLE
Windows Build Info

### ISSUE THREAD

**Issue by wini3d** [Shervanator/Engine#22]
you should probably provide what's required with Windows build? I'm guessing vs2015 only or does it work with cygwin and mingw toolchains?

checking with the stdlibc++ flag you need to use clang???

At least provide some info what tools to use in windows.

**Comment by Shervanator** [comment]
Those flags were accidentally left in and not needed anymore, https://github.com/Shervanator/Engine/pull/21 this pr fixes that, and this is the commit where we remove those flags https://github.com/Shervanator/Engine/pull/21/commits/c3e8811a00a26367d6253e819b87782f358481ef 

Ive only tested on vs2015 so far and that pr seems to work great! i dont see why other toolchains wont work, might need a bit of adjustment though, if you use them let me know what happens!
