### ISSUE TITLE
Cannot run cmake-make.sh on Ubuntu14.04

### ISSUE THREAD

**Issue by wangcan26** [Shervanator/Engine#23]
It always  reports  error:
   Clone of 'git@github.com:Perlmint/glew-cmake.git' into submodule path 'dependencies/glew' failed
   ......
  CMake Error at dependencies/CMakeLists.txt:19 (add_subdirectory):
  add_subdirectory given source "glew" which is not an existing directory.

**Comment by Shervanator** [comment]
hi hmm, i cant reproduce this issue. I've pushed this change to see if it helps at all? https://github.com/Shervanator/Engine/commit/8ed85287adcfa70b8c85302a8182501387d0391b 

You can also try cloning the project with the following command and it will try downloading all the submodules: `git clone --recursive git@github.com:Shervanator/Engine.git` that should pull all the submodules.

The other thing you can try is doing a `git clone git@github.com:Perlmint/glew-cmake.git` and see if you can even clone that repo.

Maybe you have a old version of git? Also if you look at the .gitmodules file you can see glew-cmake has a different style git url, so maybe your version of git doesn't like that?

Anyway let me know if any of this helps and i can update the instructions.

**Comment by wangcan26** [comment]
Yes it's my fault...
I havent added a ssh key on my machine.

**Comment by wangcan26** [comment]
now i can run the cmake-make.sh,  However,  when i run make ,  it reports errors:

dependencies/SDL/src/video/mir/SDL_mirsym.h:78:27: error: unknown type name ‘SDL_DYNMIRFN_mir_input_event_get_touch_event’
 SDL_MIR_SYM(MirTouchEvent const*,mir_input_event_get_touch_event,(MirInputEvent const *event))
****

..........

make[2]: *** [dependencies/SDL/CMakeFiles/SDL2.dir/src/video/mir/SDL_mirmouse.c.o] Error 1
make[1]: *** [dependencies/SDL/CMakeFiles/SDL2.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 76%] Built target assimp

**Comment by Shervanator** [comment]
hmm i haven't tried compiling this engine on ubuntu yet, i will need to test this out soon, im just fixing android builds at the moment. It sounds like this might have something to do with MIR on ubuntu, maybe disabling that in the SDL build options will fix things.

**Comment by Shervanator** [comment]
I've fixed android builds (https://github.com/Shervanator/Engine/pull/24), so i can work on linux

**Comment by Shervanator** [comment]
Okay I've tested in arch linux and it works fine, just needed one small fix: https://github.com/Shervanator/Engine/commit/57bb0624de4a95f345ac0ccebf0bc09873c2160a

Haven't tried ubuntu yet

**Comment by wangcan26** [comment]
I'm busy these days , I will try it later. nice work , nice you!

**Comment by Shervanator** [comment]
no worries :) thanks
