### ISSUE TITLE
Can not build under windows 10

### ISSUE THREAD

**Issue by Murii** [Shervanator/Engine#36]
C:\Users\Vlad\Desktop\Engine\dependencies\CMakeLists.txt:17: error: The source directory C:/Users/Vlad/Desktop/Engine/dependencies/SDL does not contain a CMakeLists.txt file.

C:\Users\Vlad\Desktop\Engine\dependencies\CMakeLists.txt:24: error: The source directory C:/Users/Vlad/Desktop/Engine/dependencies/glew does not contain a CMakeLists.txt file.

C:\Users\Vlad\Desktop\Engine\dependencies\CMakeLists.txt:164: error: The source directory C:/Users/Vlad/Desktop/Engine/dependencies/assimp does not contain a CMakeLists.txt file.

**Comment by Shervanator** [comment]
Hi there! It looks like you haven't git cloned with all the submodules.

If you are using the terminal you can clone like this:
`git clone --recursive git@github.com:Shervanator/Engine.git`

This command will go and download all the dependencies of the engine. I will add this to the readme to make it more obvious.

see this article for more help: https://stackoverflow.com/questions/3796927/how-to-git-clone-including-submodules
