### ISSUE TITLE
long time no update

### ISSUE THREAD

**Issue by jaccen** [Shervanator/Engine#60]
long time no update~~

**Comment by Shervanator** [comment]
i would love to work on it, haven't had enough time or motivation at the moment, if anyone wants to contribute anything i am more than happy to review and merge!

**Comment by jaccen** [comment]
me too, i also want to write a good  cross-platform (android, ios, windows, linux and so on )engine ,and have not enought time ,so  got your engine ,but found that have not updated recently.
my email  jaccen2007@163.com.
glad to communicate with you ~

**Comment by Shervanator** [comment]
the godot engine https://github.com/godotengine/godot is probably as good as you will get for a open source engine at the moment, but this is more meant to be a really simple engine that you can understand in a few hours of playing around with it. But yeah wish I could continue dev on it :)
