### ISSUE TITLE
Move android build into cmake

### ISSUE THREAD

**Issue by Shervanator** [Shervanator/Engine#8]

**Comment by stuaxo** [comment]
Looks like this could be a good start

https://github.com/taka-no-me/android-cmake

**Comment by Shervanator** [comment]
this pr should make this process easier, but we are still a little while off getting this fixed: https://github.com/Shervanator/Engine/pull/21

**Comment by Shervanator** [comment]
Android builds working well now with cmake after 2 years haha... https://github.com/mgerhardy/caveexpress helped quite a bit! https://github.com/Shervanator/Engine/pull/24
